### ISSUE TITLE
Web-Panel Fails To Connect To VPS

### ISSUE THREAD

**Issue by JohnathanBeaver** [Server-pro/ServerProVPSBeta#11]
**Describe the bug**
The web-panel fails to connect to the VPS.

**To Reproduce**
1. It just randomly happens- this is the second time 

**Expected behavior**
To load correctly, for server stats to be visible and for shell to load and be accessible.

**Screenshots**
https://drive.google.com/file/d/1SPwAnNP4sqnDg2E8u1L817h9vx18cSTM/view

**Additional context**
Issue resolved after VPS reset.

**Comment by sheepa** [comment]
I think this may have been caused by the following (quoting myself); If you install UFW it will block the panel from accessing your vps. The side-effect was that if you had a tab open with a server that blocked it the number of half-open websocket connections to a specific host is limited in the browser so you would then block out other servers as well.

I have added a timeout in order to fix that issue. Feel free to open a new issue if you are still having these issues.
