### ISSUE TITLE
Whole service missing after changing name

### ISSUE THREAD

**Issue by SnowmanFTW** [Server-pro/ServerProVPSBeta#4]
**Describe the bug**
The dashboard won't load, files are missing and shell is showing an error message when changing service name.

**To Reproduce**
1. Create a new service (I created a minecraft one)
2. Change name of service to something else
3. Save & Restart
4. Wait for it to finish and click on any pages, they either load infinitely or show an error.

**Expected behavior**
Well they should show the things for every page but they don't.

**Screenshots**
https://imgur.com/ZqtKunz broken dashboard, https://imgur.com/AV5CqFc error in shell

**Additional context**
To fix it you just need to close the page or go pack to the vps main page and click again on the service. Also this was done with a minecraft service, don't know if this happens with anything else.

**Comment by sheepa** [comment]
The service is identified by its name which is specified in the url. When changing the service name the url in the other open tabs are not automatically updated. While this could theoretically be fixed by an update announcement it could also come with unexpected consequences as forcing a reload of the others tabs that may contain content that you would be interested in saving.
