### ISSUE TITLE
 difference in ports

### ISSUE THREAD

**Issue by Centoller** [Server-pro/ServerProVPSBeta#6]
**Describe the bug**
Port opening works differently than normal vps and can cause confusion among users who are used to vps
This can cause an error in plugins that consult the port of the servers through a database, since all the servers will tell you that they are open on port 19132
The behavior is as if each service created is a different vps

**To Reproduce**
1- Create a pocketmine server whose port is not the default one (example port 19133)
2- check console and server.properties file
3- The server will understand that it is open on port 19132, and not the port set, however it will work with the port that appears in the dashboard
4- If you try to change the port in the server.properties file, the port set in the dashboard will stop working

**Expected behavior**
That the server.properties file, open the port set in the dashboard, and it does not always have to be in the default port

**Additional context**
What applications are you running on your server, etc.?
I run a proxy with port 19132 that connects to other pocketmine servers within the same vps

**Comment by sheepa** [comment]
Yeah as you have noticed the port is in some services (pocketmine being one of them) proxied. This is because the pocketmine image we are running doesn't support setting the ipv6 port so if you start more than once instance you'll get a port conflict. I have submitted an issue on this but until then we will have to run in scoped / proxied mode.

**Comment by sheepa** [comment]
This have now been fixed, the port set in server.properties will reflect the actual port listened on.
